apiVersion: apps/v1
kind: Deployment
metadata:
  #annotations:
  #  alpha.image.policy.openshift.io/resolve-names: "*"
  #  image.openshift.io/triggers: >-
  #    [{"from":{"kind":"ImageStreamTag","name":"sijoittaja:staging","namespace":"ohtuprojekti-staging"},"fieldPath":"spec.template.spec.containers[?(@.name==\"sijoittaja\")].image","pause":"false"}]
  name: sijoittaja-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sijoittaja
  template:
    metadata:
      labels:
        app: sijoittaja
    spec:
      containers:
        - name: sijoittaja
          image: l0uko/sijoittaja-frontend:staging
          ports:
            - containerPort: 4173
