#kind: ImageStream
#apiVersion: image.openshift.io/v1
#
#metadata:
#  name: sijoittaja
#  labels:
#    app: sijoittaja
#spec:
#  lookupPolicy:
#    local: false
#  tags:
#    - name: staging
#      from:
#        kind: DockerImage
#        name: l0uko/sijoittaja-frontend:staging
#      importPolicy:
#        scheduled: true
#      referencePolicy:
#        type: Local